### ISSUE TITLE
[SDK 2013 / Suggestion] Implement unused foley sounds and other minor assets

### ISSUE THREAD

**Issue by DoofusCockslap** [ZPSNMRiHIssues/zpsissues#240]
There are some unused foley sound effects for many things left in game since 2008.
So why not use them? 

Here are the examples:
-Collision/physics sounds for melee weapons world models. They still can be found in 2007 build files.
-Carrier footsteps, sound files of which are not present in the 2007 build, but can be found in older versions such as 1.0 or 1.2. 
-Melee impact decals for zombie claws that weren't used at all. (Flesh impact ones for example).

Edit:
-Physics sounds for gibs (obviously they are located in "Gibs" folder in ZPS folder).

**Comment by GunF0x** [comment]
I think that seems perfectly reasonable, and every little detail adds to
the depth of the game overall.

**Comment by jonnyboy0719** [comment]
I think the carrier footsteps were removed due it sounds very similar to the default, generic ones, which makes his footsteps meaningless, or that it was for gameplay reasons.

**Comment by DoofusCockslap** [comment]
I could try to edit and make Carrier footsteps sound a little more different and send you edited files back if you don‘t mind. I have some stuff in the bag for it.

**Comment by KamepeLaeske** [comment]
I don't see reason not to use them if the sounds a good enough. However, I don't see it as a big priority so I would save it for a later update. 

If you're gonna edit the footstep sounds do watch that you do not use any copyrighted material!

**Comment by jonnyboy0719** [comment]
The weapons (world ones) now use their respective collision sounds, thanks for pointing out the sound files.

**Comment by DoofusCockslap** [comment]
Don‘t worry about copyrighted material, Kaempe. I‘ll only play around with the volume, noise filtering and some hl2 sounds, since these are free to use I guess.

**Comment by KamepeLaeske** [comment]
Splendid! If you need some help, let me know :)

**Comment by AngryYoukai** [comment]
[Here is an updated version of Carrier footsteps](https://www.dropbox.com/s/83su530fqpexkts/Carrier_Footsteps_Upd1.rar?dl=0)

**Comment by DoofusCockslap** [comment]
Looked at revision 12 and Carrier has missing footsteps sounds for glass/wooden/plastic surfaces.

Also world models of mentioned melee weapons now use generic “plastic“ physics impact sound from hl2.

Is it still WIP?

**Comment by jonnyboy0719** [comment]
the build you got doesn't have all the new files, wait for sunday.

**Comment by AngryYoukai** [comment]
Ok. So in rev12 it‘s all just placeholders?

**Comment by jonnyboy0719** [comment]
about the missing footsteps;
leaf-0X (1 - 4) is missing (you can grab these from footsteps folder)

**Comment by jonnyboy0719** [comment]
regarding the plastic sounds for the carrier, i have fixed it.

**Comment by AngryYoukai** [comment]
Ok. I‘ll add the updated archive to op later today. I gotta fix the volume on some Carrier related sounds. And one more thing, if you don‘t mind I can include some additional custom sounds for melee collisions (Wrench, Sledgehammer, Pot, Frying Pan and maybe something else).

**Comment by AngryYoukai** [comment]
The game still refers to the wrong file names for glass and plastic surfaces sounds for some reason.

**Comment by DoofusCockslap** [comment]
Just spotted a small issue with the aluminium baseball bat physics sounds. Its sounds are too high pitched.

**Comment by GunF0x** [comment]
Hey guys, I probably should be removed from the GitHub for this since I am
no longer a part of the PT team. I of course will still not leak anything I
have seen, I understand what an informal NDA implies.

**Comment by Tabajara77** [comment]
Hey GunF0x, you can click "Unsubscribe" on your right there. No worries on that friend! :^)
